version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:14.17.4
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run:
          name: Lint Test (js, style)
          command: yarn lint
      - run:
          name: Unit Test
          command: yarn test
workflows:
  version: 2.1
  unit_test:
    jobs:
      - test

